package be.hogent.faith.domain.models

import be.hogent.faith.domain.models.goals.Goal
import java.util.UUID

private const val MAX_AMOUNT_OF_ACTIVE_GOALS = 5

// TODO change to value of the colors
object SkyscraperColors {
    val color1 = 1
    val color2 = 2
    val color3 = 3
    val color4 = 4
    val color5 = 5
}

data class User(
    val username: String,
    /**
     * The name of the avatar this user chose.
     * This should be unique, and will be used to request the image corresponding to the chosen avatar.
     */
    val avatarName: String,
    // generated by Firebase, and they don't generate valid UUID's
    val uuid: String
) {
    private var _events = HashMap<UUID, Event>()
    val events: List<Event>
        get() = _events.values.toList()

    private var _goals = HashMap<UUID, Goal>()
    val goals: List<Goal>
        get() = _goals.values.toList()

    private var _colors = Array(MAX_AMOUNT_OF_ACTIVE_GOALS) { SkyscraperColors.color1; SkyscraperColors.color2; SkyscraperColors.color3; SkyscraperColors.color4; SkyscraperColors.color5 }

    private var _activeGoals = arrayOfNulls<Goal>(MAX_AMOUNT_OF_ACTIVE_GOALS)
    val activeGoals: List<Goal?>
        get() = _activeGoals.toList()

    val backpack = Backpack()

    val cinema = Cinema()

    fun addEvent(event: Event) {
        if (event.title.isNullOrBlank()) {
            throw IllegalArgumentException("Een gebeurtenis moet een ingevulde titel hebben.")
        }
        _events[event.uuid] = event
    }

    fun getEvent(eventUUID: UUID): Event? {
        return _events[eventUUID]
    }

    fun clearEvents() {
        _events = HashMap()
    }

    fun removeEvent(event: Event) {
        _events.remove(event.uuid)
    }

    fun addGoal() {
        require(numberOfCompletedGoals() < MAX_AMOUNT_OF_ACTIVE_GOALS) { "Er kunnen maximum 5 actieve doelen zijn." }
        val indexToAdd = _activeGoals.indexOf(_activeGoals.first { e -> e == null })
        val goal = Goal(color = _colors[indexToAdd])
        _activeGoals[indexToAdd] = goal
        _goals[goal.uuid] = goal
    }

    fun setGoalCompleted(goal: Goal) {
        goal.toggleCompleted()
        if (goal.isCompleted)
            _activeGoals[_activeGoals.indexOf(goal)] = null
        else if (numberOfCompletedGoals() < MAX_AMOUNT_OF_ACTIVE_GOALS)
            _activeGoals[_activeGoals.indexOf(goal)] = goal
    }

    private fun numberOfCompletedGoals() = goals.filter { go -> go.isCompleted }.size
}
