package be.hogent.faith.domain.models

import be.hogent.faith.domain.models.goals.Goal
import java.util.UUID

data class User(
    val username: String,
    /**
     * The name of the avatar this user chose.
     * This should be unique, and will be used to request the image corresponding to the chosen avatar.
     */
    val avatarName: String,
    // generated by Firebase, and they don't generate valid UUID's
    val uuid: String
) {
    private var _events = HashMap<UUID, Event>()
    val events: List<Event>
        get() = _events.values.toList()

    private var _goals = HashMap<UUID, Goal>()
    val goals: List<Goal>
    get() = _goals.values.toList()

    val backpack = Backpack()

    val cinema = Cinema()

    fun addEvent(event: Event) {
        if (event.title.isNullOrBlank()) {
            throw IllegalArgumentException("Een gebeurtenis moet een ingevulde titel hebben.")
        }
        _events[event.uuid] = event
    }

    fun getEvent(eventUUID: UUID): Event? {
        return _events[eventUUID]
    }

    fun clearEvents() {
        _events = HashMap()
    }

    fun removeEvent(event: Event) {
        _events.remove(event.uuid)
    }

    fun addGoal(){
        if(goals.filter { go -> go.isCompleted }.size >= 5)
            throw IllegalArgumentException("Er kunnen maximum 5 actieve doelen zijn.")
        val goal = Goal()
        _goals[goal.uuid] = goal
    }
}
